### ISSUE TITLE
coffee check app

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/rails-two-model-CRUD#1]
https://github.com/megancoyle/coffee_check

Comfort: 5
Completeness: 5

I set up user authentication for this with Devise, but wanted to try to get ActionMailer to work but kept running into issues with it yesterday. If you have a good tutorial to point me to, that would be great. Also, I ran into a bug that I didn't want to spend too much time with - with the render "new" or render "edit" in my drinks and comments controller, I noticed  that the url structure would change when the user tried to submit the form and it didn't validate. Is there any way to resolve that? Thanks!

**Comment by andrewsunglaekim** [comment]
I'm not entirely sure how the URL changes, but i imagine the url should be the same as the request that was sent to render it.  👍  Good work! Also never really worked with actionmailer, but i hear its pretty simple
