### ISSUE TITLE
Chris-Phillips Kanban Productivity App

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/rails-two-model-CRUD#10]
Complete:4.0~ish(Missing websockets and User model)
Comfort: / sliding scale (was really hard then got easy as I did it and got into dev groove)

 Git Hub repo: https://github.com/chris-A-phillips/rails_kanban

I am so pumped to use this for tomorrow to get my project 2 organized and productive. 

Let' s talk about rails ERDs - 

When I wrote this out tonight it seemed really easy to build - it basically wrote itself when i was pseudo coding and thinking about it. Work hours and time allotted later I EVENTUALLY got the db, models, and controllers ready to go. Never ever ever ever ever ever underestimate ERDs, rails, or the time that goes into building these things without the scaffold command. After making a git repo and thinking I could start on my app I was immediately intimidated with how much I still had to write.

This seemed easy!

Projects have many Stories
States have many Stories
Stories have many States
Stories CAN have many projects (but why?)
Stories then have many Tasks and Tasks belong to a story. 

.....Then I realized what I had actually signed up for with these models and associations.

When I'm not sleep deprived I'll figure out how to make sure states are unique to projects since that's what I'm rendering to display the Kanban app(now states just get rendered in every project "SAD"). Styling this was also pretty fun with bootstrap and sass. Again, I can't stress how important this app will be for planning and making progress on project two (even though I may have cheated a bit this week by writing the base routes, models, and scripts for the base set-up.

I got user auth going on my project two base, but doing it in a single night for this kind of app was extremely daunting. I thought after doing it once (also along with andy for his lecture) that devise would become easier. After running it and trying it out at the inital setup I decided it would be INSANE to get it working with the models I had (collaborative projects sounded a little deep for one night of coding).

Next steps for this would be user auth, user collaboration (projects can belong to many users) etc. Adding lanes, updating task and story functionality with images/video models. The list goes on with this kind of app. It's basically "Build Trello". 

It's CRAZY that this past weekend I was on the struggle bus with Hogwarts and now I can build this kind of app in a night.

Good fun - super cool - can't wait to keep doing this kind of thing - talk later - sleep now

-cp-

**Comment by nayana487** [comment]
👍
