### ISSUE TITLE
Winston Art Portfolio

### ISSUE THREAD

**Issue by zorba-strange** [ga-wdi-exercises/rails-two-model-CRUD#12]
CL_4
C_1
This  week was a tired week. I lost two nights to vim and tmux playing and thus was exhausted for the remaining days. I didn't get the CRUD functionality up yet. But this will by my Art Portfolio page  so i am going to keep working on it and plan to have one model fully CRUD by the end of the day.

**Comment by zorba-strange** [comment]
https://github.com/zorba-strange/art-portfolio

**Comment by superbuggy** [comment]
comments in PR!

**Comment by superbuggy** [comment]
👍
