### ISSUE TITLE
Taylor - hw 8/5/16

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/rails-two-model-CRUD#13]
https://github.com/tedwards1884/flight_app

Comfort: 4
Completeness: 2.5

Comments: Partial 2-model CRUD... It's not incomplete because I don't know how to do it, just because I hit a mental / physical wall this week and I prioritized going over the lessons material over the homework. That said, I'm going to be using these models for my Project 2 (I've got some ideas on things I want to explore / implement), so I'll very likely be making commits here over the weekend.

I'm confident in working w/in an application to attain CRUD functionality, and roughly equally as confident in my ability to set up an application from scratch - but especially when it comes to the setup, I'm less confident that the way I'm doing it is the "most Rails-y way". I'm an improviser by training, so working from a "script" (i.e. with an emphasis on convention over flexibility) has been a bit out of my comfort zone.

**Comment by andrewsunglaekim** [comment]
maybe think of conventions as prompts? lol. When you get into heavier (not just CRUD) production rails apps. You'll see that almost everything you do in that application isn't to a mold. Take a look at our Garnet source code, very little of that is scaffolded codel. Maybe only about 10 % of the app. 👍
