### ISSUE TITLE
Chase Rails app HW complete

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/rails-two-model-CRUD#14]
https://github.com/chaseTfreeman/recipe_box

Comfort: 4

completeness: 3 - its got most functionality but its butt-ugly and the UX is terrible. 

 I got my self twisted up because I started using bootstrap and then took it out because I wanted to have time to get the HW done. So that actually ate up more time because I delete <%= yield %> which caused a bunch of problems but ultimately I learned a lot in trying to solve stuff. 

Then I also started doing a many to many model but realized I didn't have enough time for the HW mvp (the theme is that I underestimated the time we would have to work on the HW and I didn't want to copy/paste the GOT HW and change a few things) 

In the end I went back to the many to one model and did just copy most of GOT and convert it over. I'm now having styling issues.. yay! 

I'm going to continue to use this for my Project 2 because I really like the concept and I have most of the many to many stuff done.

**Comment by andrewsunglaekim** [comment]
👍 good luck sir!
