### ISSUE TITLE
Juliet Berman 2 Model Crud Homework

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/rails-two-model-CRUD#19]
I wasn't originally sure whether I was going to use this as my hw or project, so I didn't fork the original repo and instead have the files here: https://github.com/julietberman/dog_adoption

Sorry for any inconvenience!

Comfort: 4.5 (still need to learn more about validation/flash)
Completion: 5

**Comment by superbuggy** [comment]
don't sweat it! 👍 👍
