### ISSUE TITLE
Tyler Rosenberg - Blockbuster

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/rails-two-model-CRUD#5]
Comfort: 4.3
Completeness: 4

Link to app: https://github.com/TyRyanR/blockbuster

This was AMAZING! I actually got the many to many relationship to work! Although I didn't create the functionality in the form of a button to add a movie to a particular store, I created an instance in the join table using rails console, and it showed up working perfectly fine in my app! I was so excited, because I was about to give up due to the fact that I couldn't understand how the join table would relate the two, and then something just clicked and I immediately knew how to implement it.

I know there is NO CSS, but this was just more for me to execute functionality. I was very excited to see that the movie Furious 7 shows up in a certain Blockbuster branch location, and also when you click on the show page for Furious 7, it shows all the locations that movie exists at. Eventually, the app would need a button functionality which allows you to simply click in order to add that movie to a particular branch. However, right now, movies and blockbuster stores are totally separate. I was able to utilize the power of the join table to show which stores contain which movies, because each store has many movies, and each movie can belong to many stores.

I will definitely be utilizing this many to many for project 2, along with probably some nested resources!

**Comment by nayana487** [comment]
👍
