### ISSUE TITLE
Courtney's Chore-ganizer

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-wdi-exercises/rails-two-model-CRUD#9]
https://github.com/CourtneySeitz/Chore-ganizer

Comfort-level: 3.5-ish
Completeness: 3.5-ehh

First model working, second model partially-mostly working.  'Delete' and now 'Create' for the second model was/is not routing properly with the nested, wild madness I have spawned, and my brain is too tired to make it all happen tonight. I see where I need to fix my routes, but I'm too foggy to get through it. Didn't get to spend too much time on time on this, but it was super fun making it. Wish I could have done more, such as authentication and alerts and all the fun. Goooo chores!!

**Comment by nayana487** [comment]
👍
